### PR TITLE
2 ignore files when scanning for components

### PR DESCRIPTION
**Pull request by arturopie**
Solves #2 

I also added documentation on how to use this gem from a spec. This way, a CI pipeline could also check for dependency inconsistencies.

### CODE REVIEW

**Comment by dugancathal** [comment]
Ah! This is great - thanks! I really appreciate you putting in the time and effort on this.

To be honest, I didn't really understand what you meant by "ignore all files" but you meant _file_ as opposed to _directory_. Got it 👍 

If you can rebase the two code changes together, I think this PR is perfect.

**Comment by arturopie** [comment]
@dugancathal  I squashed the 2 code changes commits together. Let me know if it looks good now

**Comment by dugancathal** [comment]
Looks good! Thank you so much for the PR.

**Comment by dugancathal** [comment]
Closes #2

**Comment by arturopie** [comment]
Thanks @dugancathal. Please, let me know when this change is released to Rubygems

**Comment by dugancathal** [comment]
@arturopie All done. It's pushed under v1.0.0. (P.S. sorry that took so long)

**Pull request merged**
