### PR TITLE
let rake task fail when it founds dependencies mismatch

### PR DESCRIPTION
**Pull request by senid231**

### CODE REVIEW

**Comment by dugancathal** [comment]
Hello @senid231!

I'm so sorry for the delayed response. Thank you so much for your PR!

I just checked out your code from the PR and it looks like there's a test failure. If you can get that shored up, I'd be happy to accept this change.

Thanks again!
TJ

**Comment by senid231** [comment]
@dugancathal Hi

I've fixed specs

**Comment by senid231** [comment]
BTW it would be cool if you add `.travis.yml`

I think with some minimal config (like below) it will work

```yaml
language: ruby
rvm:
  - 2.2.4
before_install: gem install bundler -v 1.17.3
```

**Comment by dugancathal** [comment]
Done! Huge thank you, @senid231. 

I released this as version `2.0.0` to rubygems.

I've also added the `.travis.yml` - great call.

**Pull request merged**
